Feature/credit card closing info
maestrano/ofx pull request #2
Opened 2018-11-27 04:46 UTC by xiuzhong

2018-11-27 07:40 UTC, ouranos requested changes
Code looks good to me (a part from the version) but `staging` is an integration branch so we shouldn't branch off of it.

Look at how the other branches are structured:
- branched off of `master`
- PR open against the upstream repo
- Pulled into `staging` while waiting for the PR to be merged

So you should branch off of `master` and open a PR on the upstream repo  (annacruz), then ping me and I'll pull it in our `staging` branch

2018-11-27 07:40 UTC, ouranos commented on lib/ofx/parser/ofx220.rb
> +      def credit_card_closing_info
This is present in the OFX 1.0.2 specs so you should put this method in the 1.0.2 parser

2018-11-29 14:01 UTC, iseessel approved these changes
LGTM -- just one suggestion.

2018-11-29 14:01 UTC, iseessel commented on lib/ofx/parser/ofx102.rb
> +        amount.nil? || amount.empty? ? nil : to_decimal(amount)
can you use `amount.present?`:

`amount.present? ? to_decimal(amount) : nil`

2018-11-29 14:01 UTC, iseessel commented on lib/ofx/parser/ofx102.rb
> +        amount.nil? || amount.empty? ? nil : to_decimal(amount)
```
2.3.4 :003 > ''.present?
 => false
2.3.4 :004 > [].present?
 => false
2.3.4 :005 > nil.present?
 => false
2.3.4 :006 > false.present?
 => false
```

2018-11-29 14:01 UTC, iseessel commented on lib/ofx/parser/ofx102.rb
> +        date.nil? || date.empty? ? nil : build_date(date)
same as above.

2018-11-29 15:07 UTC, iseessel commented on spec/ofx/credit_card_closing_info_spec.rb
> +        @credit_card_closing_info.opening_balance.should == nil
Can we add a spec with a non `nil` opening balance?

2018-12-12 04:33 UTC, ouranos commented
Included in #5

2018-12-12 04:33 UTC, closed without merging